version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ./tit
    ports:
      - "8080:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rate-of-things
      - POSTGRES_PASSWORD=rat123456
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  react-app:
    build: 
      context: ./web 
      dockerfile: Dockerfile 
    volumes:
      - ./web:/app  
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=development 
    depends_on:
      - api

volumes:
  db-data: 
    name: db-data
    driver: local
